# Generated by Django 5.0 on 2025-07-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='birthdayInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personName', models.CharField(max_length=50)),
                ('birthDate', models.DateField()),
                ('phoneNumber', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('matric', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
            ],
        ),
    ]
