# Generated by Django 5.0 on 2025-07-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_birthdayinfo_community_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdayinfo',
            name='personImage',
            field=models.ImageField(null=True, upload_to='Birthday Images'),
        ),
    ]
