# Generated by Django 5.0 on 2025-07-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_birthdayinfo_personimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdayinfo',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='birthdayinfo',
            name='reminderDays',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='birthdayinfo',
            name='trainingLevel',
            field=models.CharField(choices=[('baptisimal', 'Baptisimal'), ('believers', 'Believers'), ('workers-in-training', 'Workers In Training'), ('completed', 'Completed')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='birthdayinfo',
            name='personImage',
            field=models.ImageField(blank=True, null=True, upload_to='Birthday Images'),
        ),
    ]
