# Generated by Django 5.0 on 2025-07-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_adminprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
