# Generated by Django 5.0 on 2025-07-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_adminprofile_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='community_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
