# Generated by Django 5.0 on 2025-08-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_adminprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthdayinfo',
            name='phoneNumber',
            field=models.CharField(max_length=15),
        ),
    ]
