# Generated by Django 5.1.1 on 2025-11-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_notificationlog_notificationpreference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='adminImage',
            field=models.ImageField(blank=True, null=True, upload_to='admin_images'),
        ),
        migrations.AlterField(
            model_name='birthdayinfo',
            name='personImage',
            field=models.ImageField(blank=True, null=True, upload_to='birthday_images'),
        ),
    ]
