# Generated by Django 5.1.1 on 2025-11-13 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_alter_adminprofile_adminimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='birthday',
        ),
    ]
