# Generated by Django 5.1.1 on 2025-11-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_remove_adminprofile_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='adminImage',
            field=models.ImageField(blank=True, null=True, upload_to='admin_images/'),
        ),
        migrations.AlterField(
            model_name='birthdayinfo',
            name='personImage',
            field=models.ImageField(blank=True, null=True, upload_to='birthday_images/'),
        ),
    ]
